/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const CognitiveLoadEntry = IDL.Record({
  'stressLevel' : IDL.Nat,
  'userId' : UserId,
  'confidenceLevel' : IDL.Nat,
  'entryId' : IDL.Text,
  'loadScore' : IDL.Float64,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'errorCount' : IDL.Nat,
  'avgTimePerQuestion' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const Result_11 = IDL.Variant({
  'ok' : CognitiveLoadEntry,
  'err' : IDL.Text,
});
export const AnalyticsSummary = IDL.Record({
  'totalCorrect' : IDL.Nat,
  'userId' : UserId,
  'weeklyStudyDays' : IDL.Vec(IDL.Nat),
  'subjectAccuracy' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'totalQuestions' : IDL.Nat,
  'cognitiveLoadTrend' : IDL.Vec(CognitiveLoadEntry),
  'totalQuizzes' : IDL.Nat,
  'overallAccuracy' : IDL.Float64,
});
export const Result_10 = IDL.Variant({
  'ok' : AnalyticsSummary,
  'err' : IDL.Text,
});
export const Recommendation = IDL.Record({
  'recType' : IDL.Text,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'targetSubject' : IDL.Text,
  'targetTopic' : IDL.Text,
  'recId' : IDL.Text,
  'reason' : IDL.Text,
});
export const DashboardData = IDL.Record({
  'recommendations' : IDL.Vec(Recommendation),
  'streakDays' : IDL.Nat,
  'recentQuizSessions' : IDL.Vec(
    IDL.Record({
      'startTime' : IDL.Int,
      'timePerQuestion' : IDL.Vec(IDL.Float64),
      'subject' : IDL.Text,
      'endTime' : IDL.Int,
      'userId' : UserId,
      'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      'difficulty' : IDL.Text,
      'score' : IDL.Nat,
      'sessionId' : IDL.Text,
      'accuracy' : IDL.Float64,
    })
  ),
  'currentCognitiveLoad' : CognitiveLoadEntry,
  'learningProgressAll' : IDL.Vec(
    IDL.Record({
      'subject' : IDL.Text,
      'progressPercentage' : IDL.Float64,
      'userId' : UserId,
      'studyStreak' : IDL.Nat,
      'lastAccessDate' : IDL.Int,
      'lastStreakDate' : IDL.Int,
      'completedTopics' : IDL.Vec(IDL.Text),
    })
  ),
  'weeklyStudySessions' : IDL.Vec(IDL.Nat),
  'profile' : IDL.Record({
    'id' : UserId,
    'notificationsEnabled' : IDL.Bool,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'studyGoalHours' : IDL.Nat,
    'themePreference' : IDL.Text,
    'email' : IDL.Text,
    'cognitiveLoadBaseline' : IDL.Float64,
    'preferredDifficulty' : IDL.Text,
  }),
});
export const Result_9 = IDL.Variant({ 'ok' : DashboardData, 'err' : IDL.Text });
export const LearningProgress = IDL.Record({
  'subject' : IDL.Text,
  'progressPercentage' : IDL.Float64,
  'userId' : UserId,
  'studyStreak' : IDL.Nat,
  'lastAccessDate' : IDL.Int,
  'lastStreakDate' : IDL.Int,
  'completedTopics' : IDL.Vec(IDL.Text),
});
export const Result_1 = IDL.Variant({
  'ok' : LearningProgress,
  'err' : IDL.Text,
});
export const MockInterviewQuestion = IDL.Record({
  'question' : IDL.Text,
  'difficulty' : IDL.Text,
  'mode' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'questionId' : IDL.Text,
  'category' : IDL.Text,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(MockInterviewQuestion),
  'err' : IDL.Text,
});
export const QuizSession = IDL.Record({
  'startTime' : IDL.Int,
  'timePerQuestion' : IDL.Vec(IDL.Float64),
  'subject' : IDL.Text,
  'endTime' : IDL.Int,
  'userId' : UserId,
  'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'difficulty' : IDL.Text,
  'score' : IDL.Nat,
  'sessionId' : IDL.Text,
  'accuracy' : IDL.Float64,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(QuizSession),
  'err' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'topicTag' : IDL.Text,
  'questionText' : IDL.Text,
  'questionId' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(QuizQuestion),
  'err' : IDL.Text,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(Recommendation),
  'err' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'notificationsEnabled' : IDL.Bool,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'studyGoalHours' : IDL.Nat,
  'themePreference' : IDL.Text,
  'email' : IDL.Text,
  'cognitiveLoadBaseline' : IDL.Float64,
  'preferredDifficulty' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const MockInterviewResult = IDL.Record({
  'strengths' : IDL.Vec(IDL.Text),
  'categoryBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'performanceFeedback' : IDL.Text,
  'improvements' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});
export const Result_3 = IDL.Variant({
  'ok' : MockInterviewResult,
  'err' : IDL.Text,
});
export const QuizResultSummary = IDL.Record({
  'cognitiveLoadCategory' : IDL.Text,
  'strongTopics' : IDL.Vec(IDL.Text),
  'recommendations' : IDL.Vec(IDL.Text),
  'weakTopics' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timeTaken' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const Result_2 = IDL.Variant({
  'ok' : QuizResultSummary,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculateCognitiveLoad' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
      ],
      [Result_11],
      [],
    ),
  'getAnalytics' : IDL.Func([IDL.Nat], [Result_10], ['query']),
  'getDashboardData' : IDL.Func([], [Result_9], ['query']),
  'getLearningProgress' : IDL.Func([IDL.Text], [Result_1], ['query']),
  'getMockInterviewQuestions' : IDL.Func([IDL.Text], [Result_8], ['query']),
  'getQuizHistory' : IDL.Func([], [Result_7], ['query']),
  'getQuizQuestions' : IDL.Func([IDL.Text, IDL.Text], [Result_6], ['query']),
  'getRecommendations' : IDL.Func([], [Result_5], ['query']),
  'getUserProfile' : IDL.Func([], [Result], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'seedQuizData' : IDL.Func([], [Result_4], []),
  'submitMockInterview' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [Result_3],
      [],
    ),
  'submitQuizSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Vec(IDL.Float64),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [Result_2],
      [],
    ),
  'updateLearningProgress' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const CognitiveLoadEntry = IDL.Record({
    'stressLevel' : IDL.Nat,
    'userId' : UserId,
    'confidenceLevel' : IDL.Nat,
    'entryId' : IDL.Text,
    'loadScore' : IDL.Float64,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'errorCount' : IDL.Nat,
    'avgTimePerQuestion' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const Result_11 = IDL.Variant({
    'ok' : CognitiveLoadEntry,
    'err' : IDL.Text,
  });
  const AnalyticsSummary = IDL.Record({
    'totalCorrect' : IDL.Nat,
    'userId' : UserId,
    'weeklyStudyDays' : IDL.Vec(IDL.Nat),
    'subjectAccuracy' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'totalQuestions' : IDL.Nat,
    'cognitiveLoadTrend' : IDL.Vec(CognitiveLoadEntry),
    'totalQuizzes' : IDL.Nat,
    'overallAccuracy' : IDL.Float64,
  });
  const Result_10 = IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text });
  const Recommendation = IDL.Record({
    'recType' : IDL.Text,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'targetSubject' : IDL.Text,
    'targetTopic' : IDL.Text,
    'recId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const DashboardData = IDL.Record({
    'recommendations' : IDL.Vec(Recommendation),
    'streakDays' : IDL.Nat,
    'recentQuizSessions' : IDL.Vec(
      IDL.Record({
        'startTime' : IDL.Int,
        'timePerQuestion' : IDL.Vec(IDL.Float64),
        'subject' : IDL.Text,
        'endTime' : IDL.Int,
        'userId' : UserId,
        'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        'difficulty' : IDL.Text,
        'score' : IDL.Nat,
        'sessionId' : IDL.Text,
        'accuracy' : IDL.Float64,
      })
    ),
    'currentCognitiveLoad' : CognitiveLoadEntry,
    'learningProgressAll' : IDL.Vec(
      IDL.Record({
        'subject' : IDL.Text,
        'progressPercentage' : IDL.Float64,
        'userId' : UserId,
        'studyStreak' : IDL.Nat,
        'lastAccessDate' : IDL.Int,
        'lastStreakDate' : IDL.Int,
        'completedTopics' : IDL.Vec(IDL.Text),
      })
    ),
    'weeklyStudySessions' : IDL.Vec(IDL.Nat),
    'profile' : IDL.Record({
      'id' : UserId,
      'notificationsEnabled' : IDL.Bool,
      'joinDate' : IDL.Int,
      'name' : IDL.Text,
      'studyGoalHours' : IDL.Nat,
      'themePreference' : IDL.Text,
      'email' : IDL.Text,
      'cognitiveLoadBaseline' : IDL.Float64,
      'preferredDifficulty' : IDL.Text,
    }),
  });
  const Result_9 = IDL.Variant({ 'ok' : DashboardData, 'err' : IDL.Text });
  const LearningProgress = IDL.Record({
    'subject' : IDL.Text,
    'progressPercentage' : IDL.Float64,
    'userId' : UserId,
    'studyStreak' : IDL.Nat,
    'lastAccessDate' : IDL.Int,
    'lastStreakDate' : IDL.Int,
    'completedTopics' : IDL.Vec(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'ok' : LearningProgress, 'err' : IDL.Text });
  const MockInterviewQuestion = IDL.Record({
    'question' : IDL.Text,
    'difficulty' : IDL.Text,
    'mode' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'questionId' : IDL.Text,
    'category' : IDL.Text,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(MockInterviewQuestion),
    'err' : IDL.Text,
  });
  const QuizSession = IDL.Record({
    'startTime' : IDL.Int,
    'timePerQuestion' : IDL.Vec(IDL.Float64),
    'subject' : IDL.Text,
    'endTime' : IDL.Int,
    'userId' : UserId,
    'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'difficulty' : IDL.Text,
    'score' : IDL.Nat,
    'sessionId' : IDL.Text,
    'accuracy' : IDL.Float64,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Vec(QuizSession),
    'err' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'topicTag' : IDL.Text,
    'questionText' : IDL.Text,
    'questionId' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(QuizQuestion),
    'err' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Vec(Recommendation),
    'err' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'notificationsEnabled' : IDL.Bool,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'studyGoalHours' : IDL.Nat,
    'themePreference' : IDL.Text,
    'email' : IDL.Text,
    'cognitiveLoadBaseline' : IDL.Float64,
    'preferredDifficulty' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const MockInterviewResult = IDL.Record({
    'strengths' : IDL.Vec(IDL.Text),
    'categoryBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'performanceFeedback' : IDL.Text,
    'improvements' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({
    'ok' : MockInterviewResult,
    'err' : IDL.Text,
  });
  const QuizResultSummary = IDL.Record({
    'cognitiveLoadCategory' : IDL.Text,
    'strongTopics' : IDL.Vec(IDL.Text),
    'recommendations' : IDL.Vec(IDL.Text),
    'weakTopics' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timeTaken' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const Result_2 = IDL.Variant({ 'ok' : QuizResultSummary, 'err' : IDL.Text });
  
  return IDL.Service({
    'calculateCognitiveLoad' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
        ],
        [Result_11],
        [],
      ),
    'getAnalytics' : IDL.Func([IDL.Nat], [Result_10], ['query']),
    'getDashboardData' : IDL.Func([], [Result_9], ['query']),
    'getLearningProgress' : IDL.Func([IDL.Text], [Result_1], ['query']),
    'getMockInterviewQuestions' : IDL.Func([IDL.Text], [Result_8], ['query']),
    'getQuizHistory' : IDL.Func([], [Result_7], ['query']),
    'getQuizQuestions' : IDL.Func([IDL.Text, IDL.Text], [Result_6], ['query']),
    'getRecommendations' : IDL.Func([], [Result_5], ['query']),
    'getUserProfile' : IDL.Func([], [Result], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'seedQuizData' : IDL.Func([], [Result_4], []),
    'submitMockInterview' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [Result_3],
        [],
      ),
    'submitQuizSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Vec(IDL.Float64),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [Result_2],
        [],
      ),
    'updateLearningProgress' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };