/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalCorrect' : bigint,
  'userId' : UserId,
  'weeklyStudyDays' : Array<bigint>,
  'subjectAccuracy' : Array<[string, number]>,
  'totalQuestions' : bigint,
  'cognitiveLoadTrend' : Array<CognitiveLoadEntry>,
  'totalQuizzes' : bigint,
  'overallAccuracy' : number,
}
export interface CognitiveLoadEntry {
  'stressLevel' : bigint,
  'userId' : UserId,
  'confidenceLevel' : bigint,
  'entryId' : string,
  'loadScore' : number,
  'timestamp' : bigint,
  'category' : string,
  'errorCount' : bigint,
  'avgTimePerQuestion' : number,
  'accuracy' : number,
}
export interface DashboardData {
  'recommendations' : Array<Recommendation>,
  'streakDays' : bigint,
  'recentQuizSessions' : Array<
    {
      'startTime' : bigint,
      'timePerQuestion' : Array<number>,
      'subject' : string,
      'endTime' : bigint,
      'userId' : UserId,
      'answers' : Array<[string, string]>,
      'difficulty' : string,
      'score' : bigint,
      'sessionId' : string,
      'accuracy' : number,
    }
  >,
  'currentCognitiveLoad' : CognitiveLoadEntry,
  'learningProgressAll' : Array<
    {
      'subject' : string,
      'progressPercentage' : number,
      'userId' : UserId,
      'studyStreak' : bigint,
      'lastAccessDate' : bigint,
      'lastStreakDate' : bigint,
      'completedTopics' : Array<string>,
    }
  >,
  'weeklyStudySessions' : Array<bigint>,
  'profile' : {
    'id' : UserId,
    'notificationsEnabled' : boolean,
    'joinDate' : bigint,
    'name' : string,
    'studyGoalHours' : bigint,
    'themePreference' : string,
    'email' : string,
    'cognitiveLoadBaseline' : number,
    'preferredDifficulty' : string,
  },
}
export interface LearningProgress {
  'subject' : string,
  'progressPercentage' : number,
  'userId' : UserId,
  'studyStreak' : bigint,
  'lastAccessDate' : bigint,
  'lastStreakDate' : bigint,
  'completedTopics' : Array<string>,
}
export interface MockInterviewQuestion {
  'question' : string,
  'difficulty' : string,
  'mode' : string,
  'keyPoints' : Array<string>,
  'questionId' : string,
  'category' : string,
}
export interface MockInterviewResult {
  'strengths' : Array<string>,
  'categoryBreakdown' : Array<[string, number]>,
  'performanceFeedback' : string,
  'improvements' : Array<string>,
  'score' : bigint,
  'totalQuestions' : bigint,
}
export interface QuizQuestion {
  'subject' : string,
  'difficulty' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'topicTag' : string,
  'questionText' : string,
  'questionId' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface QuizResultSummary {
  'cognitiveLoadCategory' : string,
  'strongTopics' : Array<string>,
  'recommendations' : Array<string>,
  'weakTopics' : Array<string>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timeTaken' : number,
  'accuracy' : number,
}
export interface QuizSession {
  'startTime' : bigint,
  'timePerQuestion' : Array<number>,
  'subject' : string,
  'endTime' : bigint,
  'userId' : UserId,
  'answers' : Array<[string, string]>,
  'difficulty' : string,
  'score' : bigint,
  'sessionId' : string,
  'accuracy' : number,
}
export interface Recommendation {
  'recType' : string,
  'userId' : UserId,
  'createdAt' : bigint,
  'targetSubject' : string,
  'targetTopic' : string,
  'recId' : string,
  'reason' : string,
}
export type Result = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_1 = { 'ok' : LearningProgress } |
  { 'err' : string };
export type Result_10 = { 'ok' : AnalyticsSummary } |
  { 'err' : string };
export type Result_11 = { 'ok' : CognitiveLoadEntry } |
  { 'err' : string };
export type Result_2 = { 'ok' : QuizResultSummary } |
  { 'err' : string };
export type Result_3 = { 'ok' : MockInterviewResult } |
  { 'err' : string };
export type Result_4 = { 'ok' : string } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<Recommendation> } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<QuizQuestion> } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<QuizSession> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<MockInterviewQuestion> } |
  { 'err' : string };
export type Result_9 = { 'ok' : DashboardData } |
  { 'err' : string };
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'notificationsEnabled' : boolean,
  'joinDate' : bigint,
  'name' : string,
  'studyGoalHours' : bigint,
  'themePreference' : string,
  'email' : string,
  'cognitiveLoadBaseline' : number,
  'preferredDifficulty' : string,
}
export interface _SERVICE {
  'calculateCognitiveLoad' : ActorMethod<
    [number, number, bigint, bigint, bigint, bigint, number, string],
    Result_11
  >,
  'getAnalytics' : ActorMethod<[bigint], Result_10>,
  'getDashboardData' : ActorMethod<[], Result_9>,
  'getLearningProgress' : ActorMethod<[string], Result_1>,
  'getMockInterviewQuestions' : ActorMethod<[string], Result_8>,
  'getQuizHistory' : ActorMethod<[], Result_7>,
  'getQuizQuestions' : ActorMethod<[string, string], Result_6>,
  'getRecommendations' : ActorMethod<[], Result_5>,
  'getUserProfile' : ActorMethod<[], Result>,
  'registerUser' : ActorMethod<[string, string], Result>,
  'seedQuizData' : ActorMethod<[], Result_4>,
  'submitMockInterview' : ActorMethod<
    [string, Array<[string, string]>],
    Result_3
  >,
  'submitQuizSession' : ActorMethod<
    [
      string,
      string,
      Array<[string, string]>,
      Array<number>,
      bigint,
      bigint,
      bigint,
    ],
    Result_2
  >,
  'updateLearningProgress' : ActorMethod<[string, string], Result_1>,
  'updateUserProfile' : ActorMethod<
    [string, string, bigint, string, string, boolean],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];