/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuizResultSummary {
    cognitiveLoadCategory: string;
    strongTopics: Array<string>;
    recommendations: Array<string>;
    weakTopics: Array<string>;
    score: bigint;
    totalQuestions: bigint;
    timeTaken: number;
    accuracy: number;
}
export interface MockInterviewQuestion {
    question: string;
    difficulty: string;
    mode: string;
    keyPoints: Array<string>;
    questionId: string;
    category: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: QuizResultSummary;
} | {
    __kind__: "err";
    err: string;
};
export interface CognitiveLoadEntry {
    stressLevel: bigint;
    userId: UserId;
    confidenceLevel: bigint;
    entryId: string;
    loadScore: number;
    timestamp: bigint;
    category: string;
    errorCount: bigint;
    avgTimePerQuestion: number;
    accuracy: number;
}
export interface MockInterviewResult {
    strengths: Array<string>;
    categoryBreakdown: Array<[string, number]>;
    performanceFeedback: string;
    improvements: Array<string>;
    score: bigint;
    totalQuestions: bigint;
}
export type Result_6 = {
    __kind__: "ok";
    ok: Array<QuizQuestion>;
} | {
    __kind__: "err";
    err: string;
};
export interface QuizQuestion {
    subject: string;
    difficulty: string;
    explanation: string;
    correctAnswer: string;
    topicTag: string;
    questionText: string;
    questionId: string;
    optionA: string;
    optionB: string;
    optionC: string;
    optionD: string;
}
export interface DashboardData {
    recommendations: Array<Recommendation>;
    streakDays: bigint;
    recentQuizSessions: Array<{
        startTime: bigint;
        timePerQuestion: Array<number>;
        subject: string;
        endTime: bigint;
        userId: UserId;
        answers: Array<[string, string]>;
        difficulty: string;
        score: bigint;
        sessionId: string;
        accuracy: number;
    }>;
    currentCognitiveLoad: CognitiveLoadEntry;
    learningProgressAll: Array<{
        subject: string;
        progressPercentage: number;
        userId: UserId;
        studyStreak: bigint;
        lastAccessDate: bigint;
        lastStreakDate: bigint;
        completedTopics: Array<string>;
    }>;
    weeklyStudySessions: Array<bigint>;
    profile: {
        id: UserId;
        notificationsEnabled: boolean;
        joinDate: bigint;
        name: string;
        studyGoalHours: bigint;
        themePreference: string;
        email: string;
        cognitiveLoadBaseline: number;
        preferredDifficulty: string;
    };
}
export interface AnalyticsSummary {
    totalCorrect: bigint;
    userId: UserId;
    weeklyStudyDays: Array<bigint>;
    subjectAccuracy: Array<[string, number]>;
    totalQuestions: bigint;
    cognitiveLoadTrend: Array<CognitiveLoadEntry>;
    totalQuizzes: bigint;
    overallAccuracy: number;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Array<Recommendation>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: DashboardData;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: LearningProgress;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export type Result_11 = {
    __kind__: "ok";
    ok: CognitiveLoadEntry;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: MockInterviewResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: AnalyticsSummary;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Array<MockInterviewQuestion>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_7 = {
    __kind__: "ok";
    ok: Array<QuizSession>;
} | {
    __kind__: "err";
    err: string;
};
export interface Recommendation {
    recType: string;
    userId: UserId;
    createdAt: bigint;
    targetSubject: string;
    targetTopic: string;
    recId: string;
    reason: string;
}
export interface QuizSession {
    startTime: bigint;
    timePerQuestion: Array<number>;
    subject: string;
    endTime: bigint;
    userId: UserId;
    answers: Array<[string, string]>;
    difficulty: string;
    score: bigint;
    sessionId: string;
    accuracy: number;
}
export interface UserProfile {
    id: UserId;
    notificationsEnabled: boolean;
    joinDate: bigint;
    name: string;
    studyGoalHours: bigint;
    themePreference: string;
    email: string;
    cognitiveLoadBaseline: number;
    preferredDifficulty: string;
}
export interface LearningProgress {
    subject: string;
    progressPercentage: number;
    userId: UserId;
    studyStreak: bigint;
    lastAccessDate: bigint;
    lastStreakDate: bigint;
    completedTopics: Array<string>;
}
export interface backendInterface {
    calculateCognitiveLoad(accuracy: number, avgTimeSecs: number, errorCount: bigint, stressLevel: bigint, confidenceLevel: bigint, retryCount: bigint, sessionDurationMins: number, topicDifficulty: string): Promise<Result_11>;
    getAnalytics(daysBack: bigint): Promise<Result_10>;
    getDashboardData(): Promise<Result_9>;
    getLearningProgress(subject: string): Promise<Result_1>;
    getMockInterviewQuestions(mode: string): Promise<Result_8>;
    getQuizHistory(): Promise<Result_7>;
    getQuizQuestions(subject: string, difficulty: string): Promise<Result_6>;
    getRecommendations(): Promise<Result_5>;
    getUserProfile(): Promise<Result>;
    registerUser(name: string, email: string): Promise<Result>;
    seedQuizData(): Promise<Result_4>;
    submitMockInterview(mode: string, answers: Array<[string, string]>): Promise<Result_3>;
    submitQuizSession(subject: string, difficulty: string, answers: Array<[string, string]>, timePerQuestion: Array<number>, stressLevel: bigint, confidenceLevel: bigint, sessionDurationSecs: bigint): Promise<Result_2>;
    updateLearningProgress(subject: string, completedTopic: string): Promise<Result_1>;
    updateUserProfile(name: string, email: string, studyGoal: bigint, difficulty: string, theme: string, notifications: boolean): Promise<Result>;
}
import type { AnalyticsSummary as _AnalyticsSummary, CognitiveLoadEntry as _CognitiveLoadEntry, DashboardData as _DashboardData, LearningProgress as _LearningProgress, MockInterviewQuestion as _MockInterviewQuestion, MockInterviewResult as _MockInterviewResult, QuizQuestion as _QuizQuestion, QuizResultSummary as _QuizResultSummary, QuizSession as _QuizSession, Recommendation as _Recommendation, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateCognitiveLoad(arg0: number, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number, arg7: string): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCognitiveLoad(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Result_11_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCognitiveLoad(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Result_11_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(arg0: bigint): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics(arg0);
                return from_candid_Result_10_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics(arg0);
            return from_candid_Result_10_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return from_candid_Result_9_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return from_candid_Result_9_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLearningProgress(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningProgress(arg0);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningProgress(arg0);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockInterviewQuestions(arg0: string): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockInterviewQuestions(arg0);
                return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockInterviewQuestions(arg0);
            return from_candid_Result_8_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizHistory(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizHistory();
                return from_candid_Result_7_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizHistory();
            return from_candid_Result_7_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(arg0: string, arg1: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0, arg1);
                return from_candid_Result_6_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0, arg1);
            return from_candid_Result_6_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations();
                return from_candid_Result_5_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations();
            return from_candid_Result_5_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedQuizData(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.seedQuizData();
                return from_candid_Result_4_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedQuizData();
            return from_candid_Result_4_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitMockInterview(arg0: string, arg1: Array<[string, string]>): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMockInterview(arg0, arg1);
                return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMockInterview(arg0, arg1);
            return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizSession(arg0: string, arg1: string, arg2: Array<[string, string]>, arg3: Array<number>, arg4: bigint, arg5: bigint, arg6: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLearningProgress(arg0: string, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLearningProgress(arg0, arg1);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLearningProgress(arg0, arg1);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Result_10_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_MockInterviewQuestion>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<MockInterviewQuestion>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_QuizSession>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<QuizSession>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_QuizQuestion>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<QuizQuestion>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Recommendation>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Recommendation>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CognitiveLoadEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CognitiveLoadEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MockInterviewResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MockInterviewResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizResultSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuizResultSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnalyticsSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnalyticsSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DashboardData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DashboardData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LearningProgress;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LearningProgress;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
